name: 01 - Building Blocks
on: [push, workflow_dispatch]
jobs:
  Say-Hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, World!"
  
  Failed-step:
    runs-on: ubuntu-latest
    steps:
      - name: Successful step
        run: |
          echo "I will fail"
          exit 0
      - name: Say goodbye
        run: echo "GoodBye!"
        
        



